### ISSUE TITLE
This repository doesn't have a main branch

### ISSUE THREAD

**Issue by SakodaShintaro** [tier4/driving_log_replayer_v2#34]
@hayato-m126 
When I added 

```
  simulator/driving_log_replayer_v2:
    type: git
    url: https://github.com/tier4/driving_log_replayer_v2.git
    version: main
```

to simulator.repos and executed `vcs import src`, the following error occurred.

```
=== src/simulator/driving_log_replayer_v2 (git) ===
Could not checkout ref 'main': fatal: invalid reference: main
```

It seems that this repository currently doesn't have a `main` branch.

Should I use the `develop` branch instead? When will the `main` branch be created?
